### PR TITLE
Add original copyright notice that says the program is public domain

### PR DESCRIPTION
**Pull request by allardhoeve**
Please add Steve's original copyright notice. I think a COPYRIGHT file is the most obvious place.

### CODE REVIEW

**Comment by pushcx** [comment]
This is already at the end of the README with a link back to his page hosting the software, I think that's good.

**Comment by allardhoeve** [comment]
You are right. Hadn't noticed :)

**Comment by allardhoeve** [comment]
I think we should leave his copyright notice intact a bit more:

Written by : Stephen J. Friedl
             Software Consultant
             Southern California USA
             steve@unixwiz.net
             http://www.unixwiz.net/tools/

Let's add this to the README. I'll update the pull request.

**Comment by allardhoeve** [comment]
I've updated the branch. Please have a new look :)

**Comment by allardhoeve** [comment]
https://github.com/ByteInternet/lockrun/blob/add-copyright-notice/README.markdown

**Pull request closed without merging**
